name = "Kami Chan Optimized"
author = "mja00"
version = "2.0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7eb1e7a38bb467387cf3a38ebbc3467a0e5c2faa22b7027f01abec9fa19bcde"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
