name = "Kami Chan Optimized Plus"
author = "mja00"
version = "2.1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ab204d5197cd5c0a775bf26ee90cac585009cd6df9c9f09213314eb1274ad26"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
