name = "Paper Chan Optimized Plus"
author = "mja00"
version = "1.0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218e69573c0bbfc386d3904d5aaf8a91e94d4f2e52f3c530b0250b44c74df629"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2"]
