name = "Kami Chan Optimized Plus"
author = "mja00"
version = "2.0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df5ac6e3c21e254f1a1944134bd0a409e185b36cd3a3c12cbf8c4d11c6822daa"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
