name = "Kami Chan Optimized Plus"
author = "mja00"
version = "1.1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ca0e90d8c19688b3aeb24a948306d7fa2649f8b08a71f73fd5cde05f861dd11"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2"]
